import Nomor1.*;

public class Main1 {
public static void main(String[] args){
	Anjing object1 = new Anjing();
        object1.lari();
        object1.tampilkanDataAnjing();
	Ayam object2 = new Ayam();
        object2.berkokok();
        object2.tampilkanDataAyam();
	Bebek object3 = new Bebek();
        object3.Berenang();
        object3.tampilkanDataBebek();
	BelahKetupat object4 = new BelahKetupat();
        object4.hitungLuas();
	Burung object5 = new Burung();
        object5.berkicau();
	Harimau object6 = new Harimau();
        object6.Menerkam();
	JajarGenjang object7 = new JajarGenjang();
        object7.hitungLuas();
	Kucing object8 = new Kucing();
        object8.lari();
	Kuda object9 = new Kuda();
        object9.kecepatanLari();
	LayangLayang object10 = new LayangLayang();
        object10.hitungLuas();
	Lingkaran object11 = new Lingkaran();
        object11.hitungLuas();
	Mobil object12 = new Mobil();
        object12.applyBrakes(12);
	Monyet object13 = new Monyet();
        object13.memanjat();
	Motor object14 = new Motor();
        object14.speedUp(32);
	Panda object15 = new Panda();
        object15.Berenang();
	Persegi object16 = new Persegi();
        object16.hitungLuas();
	PersegiPanjang object17 = new PersegiPanjang();
        object17.Hitungluas();
	Segitiga object18 = new Segitiga();
        object18.HitungLuas();
	Singa object19 = new Singa();
        object19.Menerkam();
	Trapesium object20 = new Trapesium();
        object20.hitungLuas();
	Anjing object21 = new Anjing();
        object21.lari();
	Ayam object22 = new Ayam();
        object22.berkokok();
	Bebek object23 = new Bebek();
        object23.Berenang();
	BelahKetupat object24 = new BelahKetupat();
        object24.hitungLuas();
	Burung object25 = new Burung();
        object25.berkicau();
	Harimau object26 = new Harimau();
        object26.Menerkam();
	JajarGenjang object27 = new JajarGenjang();
        object27.hitungLuas();
	Kucing object28 = new Kucing();
        object28.lari();
	Kuda object29 = new Kuda();
        object29.kecepatanLari();
	LayangLayang object30 = new LayangLayang();
        object30.hitungLuas();
	}}